# Generated by Django 3.1.3 on 2020-12-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201207_0635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myaccount',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='myaccount',
            old_name='is_admin',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='myaccount',
            old_name='is_staff',
            new_name='staff',
        ),
        migrations.AlterField(
            model_name='myaccount',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=None),
        ),
        migrations.AlterField(
            model_name='myaccount',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=None),
        ),
        migrations.AlterField(
            model_name='myaccount',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
