# Generated by Django 3.1.3 on 2020-12-07 05:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201207_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='myaccount',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
