# Generated by Django 3.1.3 on 2020-12-07 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20201207_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myaccount',
            name='dob',
        ),
    ]
