# Generated by Django 3.1.4 on 2020-12-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_myaccount_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='myaccount',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
    ]
