# Generated by Django 3.1.4 on 2020-12-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('material_type', models.CharField(choices=[('statute', 'statute'), ('act', 'act'), ('paper', 'paper'), ('article', 'article')], max_length=60)),
                ('description', models.TextField()),
            ],
        ),
    ]
