# Generated by Django 3.1.4 on 2020-12-19 01:36

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stationery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationery_profile', models.ImageField(upload_to='')),
                ('stationery_name', models.CharField(max_length=100)),
                ('stationery_location', models.CharField(max_length=100)),
                ('Stationery_slug', models.SlugField(max_length=200)),
                ('Stationery_progress', models.FilePathField()),
                ('Stationery_service_offer', multiselectfield.db.fields.MultiSelectField(choices=[('Individual Assignment', 'Individual Assignment'), ('Group Assignment', 'Group Assignment'), ('Report', 'Report'), ('Research', 'Research'), ('Paper', 'Paper')], max_length=60)),
            ],
        ),
    ]
