# Generated by Django 3.1.4 on 2020-12-19 02:22

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0003_auto_20201219_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationery',
            name='Stationery_service_offer',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Individual Task', 'Individual Task'), ('Group Task', 'Group Task'), ('Report', 'Report'), ('Research', 'Research'), ('Paper', 'Paper')], max_length=48),
        ),
    ]
