# Generated by Django 3.1.4 on 2020-12-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0005_auto_20201219_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationery',
            name='stationery_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
