# Generated by Django 3.1.3 on 2020-12-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrintingService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasktype', models.CharField(max_length=50)),
                ('slug', models.TextField()),
                ('timeframe', models.DateTimeField()),
                ('uploaddocument', models.FileField(upload_to='')),
                ('locationfordelivery', models.CharField(max_length=50)),
                ('payment', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('comment', models.TextField()),
            ],
        ),
    ]
