# Generated by Django 3.1.4 on 2020-12-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stationery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationery_profile', models.ImageField(upload_to='')),
                ('stationery_name', models.CharField(max_length=100)),
                ('stationery_location', models.CharField(max_length=100)),
                ('Stationery_slug', models.SlugField(max_length=200)),
                ('Stationery_progress', models.FilePathField()),
            ],
        ),
    ]
