# Generated by Django 3.1.4 on 2020-12-19 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0002_stationery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stationery',
        ),
    ]
